packages:
  # all packages in direct subdirs of packages/
  - "client/**"
  # all packages in subdirs of components/
  - "server/**"
  - "shared/**"
  # all packages in direct subdirs of packages/
  - "apps/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
