#!/bin/sh

# Get list of changed filenames in the staged area
CHANGED_FILES=$(git diff --cached --name-only)

# Check if there are any changes
if [ -z "$CHANGED_FILES" ]; then
  echo "No changes to commit. Exiting..."
  exit 0
fi

# Optionally, run other tasks (e.g., generating documentation)
# npm run docs

# Stage generated documentation files
git add public/docs

# Continue with the commit process
exit 0
